GET http://localhost:3000/api/get/getTask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthZWRtYWNhYmFudGlAZ21haWwuY29tIiwidXNlcklkIjoiNjZjNmY0MmNiOGEzOTYyYzU1OTY1ZDVjIiwiaWF0IjoxNzI0MzE0NjY5LCJleHAiOjE3MjQ0MDEwNjl9.dNwQvklDDI0h-fyAHnYfuWg1JxaflExE5OFk8NoDybA

###
GET http://localhost:3000/api/get/userDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthZWRtYWNhYmFudGlAZ21haWwuY29tIiwidXNlcklkIjoiNjZjNmY0MmNiOGEzOTYyYzU1OTY1ZDVjIiwiaWF0IjoxNzI0MzE0NjY5LCJleHAiOjE3MjQ0MDEwNjl9.dNwQvklDDI0h-fyAHnYfuWg1JxaflExE5OFk8NoDybA

###
GET http://localhost:3000/api/get/jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthZWRtYWNhYmFudGlAZ21haWwuY29tIiwidXNlcklkIjoiNjZjNmY0MmNiOGEzOTYyYzU1OTY1ZDVjIiwiaWF0IjoxNzI0MzE0NjY5LCJleHAiOjE3MjQ0MDEwNjl9.dNwQvklDDI0h-fyAHnYfuWg1JxaflExE5OFk8NoDybA

###
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlcm5hbWUiLCJ1c2VySWQiOiI2NmM0M2E1NzJhNjA3ZjA3N2M1OWUzMWYiLCJpYXQiOjE3MjQzMDkzNjUsImV4cCI6MTcyNDkxNDE2NX0.nz9hiRQD1rLWg1F45a1mP9PWL7nuQqbmZxAo6Qhi6lk"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlcm5hbWUiLCJ1c2VySWQiOiI2NmM0M2E1NzJhNjA3ZjA3N2M1OWUzMWYiLCJpYXQiOjE3MjQzMDkzNjUsImV4cCI6MTcyNDkxNDE2NX0.nz9hiRQD1rLWg1F45a1mP9PWL7nuQqbmZxAo6Qhi6lk"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "myusername",
  "password": "mypassword"
}

###

POST http://localhost:3000/api/post/addTask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyQGdtYWlsLmNvbSIsInVzZXJJZCI6IjY2YzZmMjZlNjE3MDNjNDU4MjNlYzQyOSIsImlhdCI6MTcyNDMxNDIyMywiZXhwIjoxNzI0NDAwNjIzfQ.Pnw57101tVOKIUH5nXFmZ64h8KqIldJw3Y9-OlBT-go
Content-Type: application/json

{
    "taskTitle": "asd",
    "taskDescription": "asd",
    "deadline": "2024-05-21",   
    "status": "In progress",
    "user_id": "66c442ae9756e2542670278f" 
}

###
PUT http://localhost:3000/api/put/updateTask/66c46818715962e3f681abd6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlcm5hbWUiLCJ1c2VySWQiOiI2NmM0M2E1NzJhNjA3ZjA3N2M1OWUzMWYiLCJpYXQiOjE3MjQyNTg1MzUsImV4cCI6MTcyNDI1OTQzNX0.paJXqF8si22rCSuZOiF5RYf2NwmIR5DcFJ017qebxmg
Content-Type: application/json

{
  "id":"66c46818715962e3f681abd6",
  "taskTitle": "Updated Task Titlse",
  "taskDescription": "Updated task description",
  "deadline": "2024-09-30T23:59:59Z",
  "status": "In progress",
  "user": "66c4685c715962e3f681abd8"
}

